name: Unit-Testing

on:
  push:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-lates

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Node Instll
        uses: actions/setup-node@v1
        with:
          node-version ${{matrix.node-version}}
      - run: npm i

      - name: Run Jest Unit-Testing
      - uses: actions/setup-node@v1
        with:
          node-version ${{matrix.node-version}}
      - run: npm run test:ci

